### ISSUE TITLE
Better error message when chistributed.conf is not found.

### ISSUE THREAD

**Issue by frank-lsf** [uchicago-cs/chistributed#1]
At this moment, if you run chistributed in a folder without the required `chistributed.conf` file, you would get:

```
/Users/luans/Library/Python/2.7/bin/chistributed
Traceback (most recent call last):
  File "/Users/luans/Library/Python/2.7/bin/chistributed", line 9, in <module>
    load_entry_point('chistributed', 'console_scripts', 'chistributed')()
  File "/Users/luans/Library/Python/2.7/lib/python/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/luans/Library/Python/2.7/lib/python/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/luans/Library/Python/2.7/lib/python/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/luans/chistributed/src/chistributed/cli/__init__.py", line 66, in chistributed_cmd
    backend = ZMQBackend(config_obj.get_node_executable(), 'tcp://127.0.0.1:23310', 'tcp://127.0.0.1:23311', debug = debug)
  File "/Users/luans/chistributed/src/chistributed/backends/zmq.py", line 88, in __init__
    self.node_executable = node_executable.split()
AttributeError: 'NoneType' object has no attribute 'split'
```

Which is non-descriptive. Should we prompt the user that the conf file does not exist?

**Comment by borjasotomayor** [comment]
Fixed in https://github.com/uchicago-cs/chistributed/commit/78fafeffaed7ea9ef83354fd4459bf77f6a63746 and https://github.com/uchicago-cs/chistributed/commit/2722c0f669a93f16f60b53d1d3b7f298eb9a6f37
